# Generated by Django 4.0.2 on 2022-02-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='email_business',
            new_name='business_email',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='phone_business',
            new_name='business_phone',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='phone_personal',
            new_name='personal_phone',
        ),
    ]
